---
- name: "Raspberry PI4 Video Mixer Automation"
  hosts: localhost
  become: false
  connection: local
  gather_facts: true

  vars_prompt:

    - name: FULLNAME
      prompt: "Full Name:                   "
      private: no
      default: "{{ lookup('env','USER', errors='ignore') | default('')}}"

    - name: JOBTITLE
      prompt: "Job Title:                   "
      private: no
      default: "{{ lookup('env','USER', errors='ignore') | default('SOLUTIONS ENGINEER')}}"

    - name: EMAIL
      prompt: "Email:                   "
      private: no
      default: "{{ lookup('env','USER', errors='ignore') | default('user@example.com')}}"

    - name: YOUTUBEUSERNAME
      prompt: "YouTube Username:        "
      private: no
      default: "{{ lookup('env','USER', errors='ignore') | default('user@example.com')}}"

    - name: FACEBOOKUSERNAME
      prompt: "Facebook Username:        "
      private: no
      default: "{{ lookup('env','USER', errors='ignore') | default('user@example.com')}}"

    - name: ATEMIP
      prompt: "Atem mini IP:    "
      private: no
      default: "{{ lookup('pipe','grep atem /etc/hosts | expand -t 1 | cut -f 1 -d \" \"', errors='ignore') | default('192.168.2.240', true)  }}"

  vars:
    HOSTNAME: "{{ lookup('pipe','raspi-config nonint get_hostname', errors='ignore') }}"
    GITHUBUSERNAME: "robinmordasiewicz"
    GITHUBPROJECT: "AV-configs"
  
  tasks:

    - name: GIT name
      git_config:
          name: user.name
          scope: global
          value: "{{ FULLNAME }}"

    - name: GIT email
      git_config:
          name: user.email
          scope: global
          value: "{{ EMAIL }}"

    - name: GIT editor
      git_config:
          name: core.editor
          scope: global
          value: vim
      
    - name: GIT credential cache
      git_config:
          name: credential.helper
          scope: global
          value: store
